services:
  classic-ml-train:
    build:
      args: 
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
      dockerfile: dockerfile-python
      context: ./
    volumes:
      - ../src:/src/
      - ${USECASE_PATH}/src:/src/app
      - ${USECASE_PATH}/dataset:/dataset
      - ${USECASE_PATH}/output:/output
      - ${USECASE_PATH}/feat:/feature_store
    working_dir: /src/app
    command:
      - /bin/bash
      - -c
      - |
        pip install -q -r requirements.txt
        python -u dataprep/data_prepare.py --train
        python -u train/train.py
    container_name: lgbm-container
    image: lgbm-image
    network_mode: "host"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - PYTHONUNBUFFERED=1