FROM ubuntu:22.04

RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 \
    python3-pip \
    python-is-python3

RUN pip install --upgrade pip
RUN pip install -U pandas numpy pyarrow jupyterlab