	# Copyright (C) 2023 Intel Corporation
	# SPDX-License-Identifier: MIT
	# Downloaded from https://github.com/intel/graph-neural-networks-and-analytics
workflow_spec:
  dataloader_params:
    batch_size: 1024
    batch_size_eval: 1000000
  sampler_params:
    fan_out: "40,40"
    #sampling fan_out per GNN layer
  model_params:
    hidden_size: 64
    num_layers: 2
    learning_rate: 0.05
  training_params:
    num_epochs: 10
    eval_every: 1
  dgl_params:
    num_trainers: 1
    num_samplers: 2
    num_servers: 1