FROM ubuntu:22.04

RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-pip python-is-python3

RUN pip install --upgrade pip
RUN pip install -U  psutil \
                    tqdm \
                    ipywidgets \
                    requests \
                    scikit-learn \
                    dgl==1.1.3 \
                    numba==0.58.1 \
                    pandas[pyarrow] \
                    pyarrow==14.0.2 \
                    torch==2.2.0 \
                    packaging